// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `footage_path`, `handle_change_callback`, `item`, `project`, `project`, `project`, `state`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeError>>
abstract class BridgeError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitBridgeState>>
abstract class LumitBridgeState implements RustOpaqueInterface {
  static LumitProject? getCurrentProject() =>
      BridgeLib.instance.api.crateApiLumitBridgeStateGetCurrentProject();

  static LumitProject newProject(
          {RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api
          .crateApiLumitBridgeStateNewProject(onChangeStream: onChangeStream);

  static LumitProject? openProject(
          {required String path,
          RustStreamSink<ScopedChange>? onChangeStream}) =>
      BridgeLib.instance.api.crateApiLumitBridgeStateOpenProject(
          path: path, onChangeStream: onChangeStream);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitComposition>>
abstract class LumitComposition implements RustOpaqueInterface {
  List<LumitLayer> getLayers();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitLayer>>
abstract class LumitLayer implements RustOpaqueInterface {
  bool equals({required LumitLayer layer});

  String getName();

  void rename({required String name});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitProject>>
abstract class LumitProject implements RustOpaqueInterface {
  List<LumitProjectItem> getItems();

  void redo();

  void undo();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LumitProjectItem>>
abstract class LumitProjectItem implements RustOpaqueInterface {
  bool equals({required LumitProjectItem item});

  LumitProjectItemInfo getInfo();

  Future<LumitMediaStatus> getStatus();
}

enum LumitMediaStatus {
  missing,
  ready,
  ;
}

class LumitProjectItemInfo {
  final LumitProjectItemType itemType;
  final String name;

  const LumitProjectItemInfo({
    required this.itemType,
    required this.name,
  });

  @override
  int get hashCode => itemType.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LumitProjectItemInfo &&
          runtimeType == other.runtimeType &&
          itemType == other.itemType &&
          name == other.name;
}

@freezed
sealed class LumitProjectItemType with _$LumitProjectItemType {
  const LumitProjectItemType._();

  const factory LumitProjectItemType.footage() = LumitProjectItemType_Footage;
  const factory LumitProjectItemType.solid() = LumitProjectItemType_Solid;
  const factory LumitProjectItemType.composition(
    LumitComposition field0,
  ) = LumitProjectItemType_Composition;
  const factory LumitProjectItemType.folder() = LumitProjectItemType_Folder;
}

class ScopedChange {
  final LumitProject project;
  final LumitProjectItem? item;
  final LumitLayer? layer;

  const ScopedChange({
    required this.project,
    this.item,
    this.layer,
  });

  @override
  int get hashCode => project.hashCode ^ item.hashCode ^ layer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScopedChange &&
          runtimeType == other.runtimeType &&
          project == other.project &&
          item == other.item &&
          layer == other.layer;
}
